export const GET_PROFILES = "GET_PROFILES";
export const NEW_PROFILE = "NEW_PROFILE";
export const REMOVE_PROFILE = "REMOVE_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const PROFILE_MODAL_DATA_LOADED = "PROFILE_MODAL_DATA_LOADED";

